apiVersion: v1
kind: Service
metadata:
  name: dadjokesdeploy01
  namespace: dadjokesdeploy01-ns
spec:
  type: LoadBalancer
  selector:
    app: dadjokesdeploy01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80