apiVersion: v1
kind: Service
metadata:
  name: dadjokes
  namespace: dadjokesns
spec:
  type: LoadBalancer
  selector:
    app: dadjokes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80